[phases.setup]
nixPkgs = ['nodejs-18_x', 'yarn']

[phases.install]
cmds = ['yarn install --frozen-lockfile --production']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'node app.js'

[variables]
NODE_ENV = 'production'