[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm install --omit=dev']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'node app.js'

[variables]
NODE_ENV = 'production'